GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/1
###
DELETE http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "name": "Ben Simmons",
    "number": "555-555-555"
}